### ISSUE TITLE
Add Format Support

### ISSUE THREAD

**Issue by arb** [stardog-union/stardog-vsc#62]
Added formatting support. This would require a SPARQL parser. While https://github.com/RubenVerborgh/SPARQL.js does a pretty good job, it does not preserve any comments so this would be a lossy format, hardly ideal.

Once we get the string how we want it, use diffjs to give us a change set, and the response back with that to apply the formats.

**Comment by jmrog** [comment]
Closing for now. Will create an issue in our language-servers repo.
